In [1]:
import pandas as pd
import geopandas as gpd
pd.set_option("display.width", 120) # Tells Pandas to change the maximum width of the console output to 120 characters before wrapping text to a new line.
# pd.set_option('display.max_columns', None) # Force Pandas to display all columns. Place before displaying your DataFrame

print("Environnement prêt")

Environnement prêt

In [2]:
df = pd.read_csv("../feature_summary.csv")
print(df.shape)
df.head() #print the first 5 columns by default

(320, 16004)

,country,admin_1,admin_2,year,planet_0_q1,planet_0_q2,planet_0_q3,planet_0_q4,planet_1_q1,planet_1_q2,...,planet_997_q3,planet_997_q4,planet_998_q1,planet_998_q2,planet_998_q3,planet_998_q4,planet_999_q1,planet_999_q2,planet_999_q3,planet_999_q4
0,Togo,Centre,Blitta,2016,0.034059,0.028130,0.007090,0.039566,0.032327,0.018890,...,0.104550,0.390826,0.086880,0.048972,0.062294,0.057653,0.603227,0.439633,0.094083,0.435992
1,Togo,Centre,Blitta,2017,0.091740,0.060450,0.073351,0.077535,0.052786,0.020566,...,0.279689,0.579065,0.168369,0.131208,0.040969,0.118672,0.320748,0.264108,0.591500,0.451850
2,Togo,Centre,Blitta,2018,0.099782,0.072666,0.109088,0.065963,0.038649,0.021820,...,0.457497,0.576939,0.206745,0.070264,0.071139,0.116523,0.353122,0.500156,0.571058,0.423053
3,Togo,Centre,Blitta,2019,0.065744,0.077545,0.116285,0.064548,0.033283,0.024243,...,0.498492,0.565818,0.167556,0.097914,0.092977,0.110927,0.304760,0.507746,0.546144,0.434186
4,Togo,Centre,Blitta,2020,0.054686,0.059825,0.066479,0.048202,0.018643,0.017654,...,0.359325,0.392158,0.112482,0.072326,0.056439,0.052037,0.288308,0.471186,0.490266,0.398532

In [3]:
df = pd.read_csv("../fews_net_yield_TGO.csv")
print(df.shape)
df.head() #print the first 5 columns by default

(893, 10)

,country,admin_1,admin_2,year,season_name,season_type,product,area_planted,quantity_produced,yield
0,Togo,Centre,Blitta,2016,Annual,Harvest,Rice (Paddy),5708.0,9152.42,1.603437
1,Togo,Centre,Blitta,2016,Main,Harvest,Beans (mixed),28489.0,12047.14,0.422870
2,Togo,Centre,Blitta,2016,Main,Harvest,Cassava,7552.0,34067.07,4.511000
3,Togo,Centre,Blitta,2016,Main,Harvest,Groundnuts (In Shell),572.0,341.13,0.596381
4,Togo,Centre,Blitta,2016,Main,Harvest,Maize (Corn),13452.0,19326.11,1.436672

In [4]:
gdf = gpd.read_file("../gadm41_TGO_2.geojson")
print(gdf.head())
print(gdf.crs)

  country admin_1    admin_2                                           geometry
0    Togo  Centre     Blitta  MULTIPOLYGON (((0.6222 7.9015, 0.6227 7.9017, ...
1    Togo  Centre         Mô  MULTIPOLYGON (((0.6173 8.5135, 0.6118 8.5127, ...
2    Togo  Centre  Sotouboua  MULTIPOLYGON (((0.9443 8.3788, 0.9321 8.3845, ...
3    Togo  Centre    Tchamba  MULTIPOLYGON (((1.2352 8.396, 1.2354 8.414, 1....
4    Togo  Centre   Tchaudjo  MULTIPOLYGON (((1.2391 8.6754, 1.2335 8.6737, ...
EPSG:4326